main:
  - weight: 1
    identifier: "posts"
    pre: ""
    post: ""
    name: "Posts"
    url: "/posts/"
    title: "Posts"
  - weight: 2
    identifier: "tags"
    pre: ""
    post: ""
    name: "Tags"
    url: "/tags/"
    title: "Tags"
  - weight: 3
    identifier: "categories"
    pre: ""
    post: ""
    name: "Categories"
    url: "/categories/"
    title: "Categories"
  - weight: 4
    identifier: "home"
    pre: "<i class=\"fa-solid fa-house\"></i>"
    post: ""
    name: ""
    url: "/"
    title: "Home"
  - weight: 5
    identifier: "about"
    pre: "<i class=\"fa-solid fa-circle-info\"></i>"
    post: ""
    name: ""
    url: "/about/"
    title: "About"
